---
title: "team.Rmd"
author: 'Chase Weida; Github: cweida; Bernard Fay: Github: bj99fay'
date: "3/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cleaning
```{r}
#defense

defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
head(defense)
defense <- data.frame(defense)
defense$Name <- as.factor(defense$Name)
defense$Opponent_Opponent <- as.factor(defense$Opponent_Opponent)

defense <- defense %>% mutate_at(.vars=c(3:11), .funs= list(as.numeric))
defClean <- defense

#offense
offense <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
offense %>% head()

offense$Name <- as.factor(offense$Name)
offense$Opponent_Opponent <- as.factor(offense$Opponent_Opponent)
offense <-separate(offense, "Passing_CMP-ATT", into=c("Passing_CMP", "Passing_ATT"), sep="-\r\n ")
offense <- mutate_at(offense, .vars=c(3:13), .funs=funs(as.numeric))

offClean <- offense

#biography

biography <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')
biography <- data.frame(biography)

biography <- biography %>% separate(Height, sep = "-", into = c('Ft', 'inch'), remove = TRUE)  
biography$Ft <- as.numeric(biography$Ft)
biography$inch <- as.numeric(biography$inch)

biography$Height <- biography %>% transmute(inches = (Ft * 12) + inch)
biography <- biography %>% select(-c(3,4))
biography <- biography %>% mutate_at(.vars = c(1,2,4,5,6), .funs = funs(as.factor)) %>% mutate_at(.vars = c(3), .funs = funs(as.numeric))
bioClean <- biography
```
